/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>      // Added this for printf
#include "spi.h"
#include "imu.h"

#define GPIOAEN     (1U << 0)
#define UART2EN     (1U << 17)
#define CR1_TE      (1U << 3)
#define CR1_UE      (1U << 13)
#define SR_TXE      (1U << 7)

void uart_init(void) {
    // 1. Enable clock access to GPIOA (for PA2)
    RCC->AHB1ENR |= GPIOAEN;

    // 2. Set PA2 to Alternate Function mode
    GPIOA->MODER &= ~(1U << 4);
    GPIOA->MODER |=  (1U << 5);

    // 3. Set PA2 alternate function type to AF7 (USART2_TX)
    GPIOA->AFR[0] |=  (1U << 8);
    GPIOA->AFR[0] |=  (1U << 9);
    GPIOA->AFR[0] |=  (1U << 10);
    GPIOA->AFR[0] &= ~(1U << 11);

    // 4. Enable clock access to UART2
    RCC->APB1ENR |= UART2EN;

    // 5. Configure baud rate (115200 @ 16MHz default)
    USART2->BRR = 0x8B;

    // 6. Enable transmitter and the UART module
    USART2->CR1 = CR1_TE;
    USART2->CR1 |= CR1_UE;
}

// Redirect printf by implementing __io_putchar
int __io_putchar(int ch) {
    // Wait until transmit data register is empty
    while (!(USART2->SR & SR_TXE)) {}
    // Write character to data register
    USART2->DR = (ch & 0xFF);
    return ch;
}

int main(void)
{
    spi1_init();
    uart_init();

    if (imu_init() == 0) {
        // If IMU fails, print error and halt
    	printf("initializing imu\r\n");

    	    // Let's see what the IMU is actually sending back
    	    uint8_t id = imu_read(IMU_WHO_AM_I);

    	    if (id != IMU_ID) {
    	        printf("failed, expected: 0x%02X, but read: 0x%02X\r\n", IMU_ID, id);
    	        while(1);
    	    }
        while(1);
    }

    printf("finish init\r\n");

    while (1) {
        volatile uint16_t steps = read_steps();
        printf("Steps: %d\r\n", steps);

        // delay for serial monitor updaet
        for(int i = 0; i < 500000; i++);
    }
}
